# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Пеленицын Артём Михайлович
tagline:          Домашняя страница
baseurl:          http://mmcs.sfedu.ru/~ulysses/new/
author:
  name:           Артём Пеленицын
  url:            https://twitter.com/ulysses4ever
  email:          ulysses4ever@gmail.com

# Custom vars
version:          0.0.1
