# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Пеленицын Артём Михайлович
tagline:          Домашняя страница
paginate:         1
baseurl:          /~ulysses/new/
author:
  name:           Артём Пеленицын
  url:            https://twitter.com/ulysses4ever
  email:          ulysses4ever@gmail.com

# Custom vars
version:          0.0.1
